[project]
python = "^3.8"

[tool.poetry]
name = "communications-manager"
version = "0.0.1-alpha"
description = "TODO"
authors = [
    #TODO add authors
]
readme = 'README.md'
license = "MIT"
repository = "https://github.com/NHSDigital/communications-manager"
homepage = ""
keywords = ["healthcare", "uk", "nhs"] #TODO add additional keywords


[tool.poetry.dependencies]
python = "^3.8"
pytest-nhsd-apim = "^3.3.2"
pyjwt = {version = "2.3.0", extras = ["crypto"]}
pytest-xdist = "^3.3.1"
pre-commit = "^3.3.3"

[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"
black = "^20.8b1"
pip-licenses = "^2.0.1"
jinja2 = "^3.1.0"
pyyaml = "^5.2"
docopt = "^0.6.2"
jsonpath-rw = "^1.4.0"
semver = "^2.9.0"
gitpython = "^3.1.30"
pytest = "^6.1.2"
coverage = "^5.5"
aiohttp = "^3.8.5"
pytest-asyncio = "^0.14.0"

[tool.poetry.scripts]
