name: PR Quality Check
on: pull_request
jobs:
  link-ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Check ticket name conforms to requirements
        env:
          BRANCH_REF: ${{ github.event.pull_request.head.ref }}
        run: echo "$BRANCH_REF" | grep -i -E -q "(ccm-[0-9]+)|(dependabot\/)"
        continue-on-error: true

      - name: Grab ticket name
        if: contains(github.event.pull_request.head.ref, 'ccm-') || contains(github.event.pull_request.head.ref, 'CCM-')
        env:
          BRANCH_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          TICKET=$(echo "$BRANCH_REF" | grep -i -o '\(ccm-[0-9]\+\)' | tr '[:lower:]' '[:upper:]')
          echo "TICKET_NAME=$TICKET" >> $GITHUB_ENV
        continue-on-error: true

      - name: Comment on PR with link to JIRA ticket
        if: contains(github.event.pull_request.head.ref, 'ccm-') || contains(github.event.pull_request.head.ref, 'CCM-')
        continue-on-error: true
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            This branch is work on a ticket in the NHS Digital APM JIRA Project. Here's a handy link to the ticket:
            # [${{ env.TICKET_NAME }}](https://nhsd-jira.digital.nhs.uk/browse/${{ env.TICKET_NAME}})

